name: gopenehr
services:
  migrate:
    image: gopenehr:test
    environment:
      DATABASE_URL: "postgres://gopenehr:gopenehrpass@postgres:5432/gopenehr?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["migrate", "up"]

  gopenehr:
    image: gopenehr:test
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://gopenehr:gopenehrpass@postgres:5432/gopenehr?sslmode=disable"
    command: ["serve"]
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/app/gopenehr", "healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
      
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: gopenehr
      POSTGRES_PASSWORD: gopenehrpass
      POSTGRES_DB: gopenehr
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "gopenehr"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s