name: gopenehr-example
services:
  migrate:
    image: ghcr.io/freekieb7/gopenehr:latest
    environment:
      DATABASE_URL: "postgres://gopenehr:gopenehrpass@postgres:5432/gopenehr?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["migrate", "up"]

  gopenehr:
    image: ghcr.io/freekieb7/gopenehr:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://gopenehr:gopenehrpass@postgres:5432/gopenehr?sslmode=disable"
      OTEL_ENDPOINT: "alloy:4317"
      OTEL_INSECURE: true
    command: ["serve"]
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/app/gopenehr", "healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
      
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: gopenehr
      POSTGRES_PASSWORD: gopenehrpass
      POSTGRES_DB: gopenehr
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "gopenehr"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  alloy:
    image: grafana/alloy:v1.11.3
    volumes:
      - ./alloy:/etc/alloy
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "12345:12345" # UI
    environment:
      GRAFANA_CLOUD_OTLP_ENDPOINT: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp
      GRAFANA_CLOUD_INSTANCE_ID: 
      GRAFANA_CLOUD_API_KEY: 
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental # Enable all functionality