name: gopenehr-example
services:
  migrate:
    image: ghcr.io/freekieb7/gopenehr:latest
    environment:
      DATABASE_URL: "postgres://gopenehr:gopenehrpass@postgres:5432/gopenehr?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["migrate", "up"]

  gopenehr:
    image: ghcr.io/freekieb7/gopenehr:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://gopenehr:gopenehrpass@postgres:5432/gopenehr?sslmode=disable"
      # KAFKA_BROKERS: kafka:9092
      # OTEL_ENDPOINT: alloy:4317
      # OTEL_INSECURE: true
    command: ["serve"]
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/app/gopenehr", "healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
      
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: gopenehr
      POSTGRES_PASSWORD: gopenehrpass
      POSTGRES_DB: gopenehr
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "gopenehr"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  # alloy:
  #   image: grafana/alloy:v1.11.3
  #   volumes:
  #     - ./alloy:/etc/alloy
  #   ports:
  #     - "4317:4317" # OTLP gRPC
  #     - "4318:4318" # OTLP HTTP
  #     - "12345:12345" # UI
  #   environment:
  #     GRAFANA_CLOUD_OTLP_ENDPOINT: https://otlp-gateway-prod-eu-west-2.grafana.net/otlp
  #     GRAFANA_CLOUD_INSTANCE_ID: 
  #     GRAFANA_CLOUD_API_KEY: 
  #   command:
  #     - run
  #     - /etc/alloy/config.alloy
  #     - --storage.path=/var/lib/alloy/data
  #     - --server.http.listen-addr=0.0.0.0:12345
  #     - --stability.level=experimental # Enable all functionality

  # kafka:
  #     image: confluentinc/cp-kafka:7.8.0
  #     hostname: kafka
  #     container_name: kafka
  #     ports:
  #       - "9092:29092"   # host:container (external)
  #       - "9093:9093"
  #     environment:
  #       KAFKA_NODE_ID: 1
  #       KAFKA_BROKER_ID: 1
  #       KAFKA_PROCESS_ROLES: 'broker,controller'
  #       KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
  #       KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092'
  #       KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,EXTERNAL://localhost:9092'
  #       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
  #       KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  #       KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  #       CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
  #       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #       KAFKA_DEFAULT_REPLICATION_FACTOR: 1
  #       KAFKA_MIN_INSYNC_REPLICAS: 1
        
  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-cluster-ui
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  #   depends_on:
  #     - kafka