services:
  gopenehr:
    image: ghcr.io/freekieb7/gopenehr:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://gopenehr:gopenehrpass@postgres:5432/gopenehr?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: gopenehr
      POSTGRES_PASSWORD: gopenehrpass
      POSTGRES_DB: gopenehr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "gopenehr"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s