services:
  pg:
    image: postgres:18
    environment:
      POSTGRES_USER: gopenehr
      POSTGRES_PASSWORD: gopenehrpass
      POSTGRES_DB: gopenehr
    ports:
      - "5432:5432"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data