services:
  # kafka1:
  #   image: confluentinc/cp-kafka:7.8.0
  #   hostname: kafka1
  #   container_name: kafka1
  #   ports:
  #     - "9092:9092"
  #     - "9093:9093"
  #   environment:
  #     KAFKA_NODE_ID: 1
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_PROCESS_ROLES: 'broker,controller'
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
  #     KAFKA_LISTENERS: 'PLAINTEXT://kafka1:19092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka1:9093'
  #     KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:19092,PLAINTEXT_HOST://localhost:9092'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  #     KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  #     KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  #     CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  #     KAFKA_MIN_INSYNC_REPLICAS: 2

  # kafka2:
  #   image: confluentinc/cp-kafka:7.8.0
  #   hostname: kafka2
  #   container_name: kafka2
  #   ports:
  #     - "9094:9094"
  #     - "9095:9093"
  #   environment:
  #     KAFKA_NODE_ID: 2
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_PROCESS_ROLES: 'broker,controller'
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
  #     KAFKA_LISTENERS: 'PLAINTEXT://kafka2:19092,PLAINTEXT_HOST://0.0.0.0:9094,CONTROLLER://kafka2:9093'
  #     KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka2:19092,PLAINTEXT_HOST://localhost:9094'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  #     KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  #     KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  #     CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  #     KAFKA_MIN_INSYNC_REPLICAS: 2

  # kafka3:
  #   image: confluentinc/cp-kafka:7.8.0
  #   hostname: kafka3
  #   container_name: kafka3
  #   ports:
  #     - "9096:9096"
  #     - "9097:9093"
  #   environment:
  #     KAFKA_NODE_ID: 3
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_PROCESS_ROLES: 'broker,controller'
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
  #     KAFKA_LISTENERS: 'PLAINTEXT://kafka3:19092,PLAINTEXT_HOST://0.0.0.0:9096,CONTROLLER://kafka3:9093'
  #     KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka3:19092,PLAINTEXT_HOST://localhost:9096'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  #     KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  #     KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  #     CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  #     KAFKA_MIN_INSYNC_REPLICAS: 2

  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   container_name: kafka-cluster-ui
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:19092,kafka2:19092,kafka3:19092
  #   depends_on:
  #     - kafka1
  #     - kafka2
  #     - kafka3

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: gopenehr
      POSTGRES_PASSWORD: gopenehrpass
      POSTGRES_DB: gopenehr
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf:ro
    command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf
    healthcheck:
      test: pg_isready -U gopenehr -d gopenehr
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

